jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git re2c libc6-dev libffi-dev
    displayName: Install Dependencies
  - bash: |
      # Used "set -ex" instead of hashbang since script isn't executed with hashbang
      set -ex

      trap "exit 1" ERR

      echo $PWD
      ls
      chmod +x compile.sh
      echo | ./compile.sh -t linux64 -j 256 -f -g
      tar -czf ./PHP_Linux-x86_64.tar.gz bin
    displayName: Build PHP
  - bash: |
      pwd
      cd $BUILD_SOURCESDIRECTORY
      pwd
      cp PHP_Linux-x86_64.tar.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
      cp install.log $BUILD_ARTIFACTSTAGINGDIRECTORY
    displayName: Copy Artifacts
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Linux'
    inputs:
      ArtifactName: Linux
    condition: succeededOrFailed()
- job: MacOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - bash: |
      brew install libtool autoconf automake pkg-config bison re2c libiconv libffi
    displayName: Install Dependencies
  - bash: |
      export PATH="/usr/local/opt/bison/bin:$PATH"
      export LDFLAGS="-L/usr/local/opt/libiconv/lib"
      export CPPFLAGS="-I/usr/local/opt/libiconv/include"
      export PATH="/usr/local/opt/libiconv/bin:$PATH"
      export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
      export LDFLAGS="-L/usr/local/opt/libffi/lib $LDFLAGS"
      export CPPFLAGS="-I/usr/local/opt/libffi/include $CPPFLAGS"
      set -ex
      trap "exit 1" ERR

      ./compile.sh -t mac64 -j 256 -f -g
      tar -czf ./PHP_MacOS-x86_64.tar.gz bin
    displayName: Build PHP
  - bash: |
      pwd
      cd $BUILD_SOURCESDIRECTORY
      pwd
      cp PHP_MacOS-x86_64.tar.gz $BUILD_ARTIFACTSTAGINGDIRECTORY
      cp install.log $BUILD_ARTIFACTSTAGINGDIRECTORY
    displayName: Copy Artifacts
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Mac'
    inputs:
      ArtifactName: Mac
    condition: succeededOrFailed()
